### ISSUE TITLE
Two times "Open Files" entry 

### ISSUE THREAD

**Issue by odlevakp** [oriolmirosa/open-files#17] opened 2017-06-07 11:01 UTC
After installing, I can see the "Open Files" entry 2x, first contains opened files, second one is empty.

![screen shot 2017-06-07 at 12 58 30](https://user-images.githubusercontent.com/6029696/26875256-5744104e-4b81-11e7-89f6-9e5f58da6de2.png)

**Comment by oriolmirosa** [comment] 2017-06-07 13:34
Thanks for reporting this. Can you give me some more information? What version of Atom are you using? What packages are loaded? How many panels are open? Any other info that could help me reproduce the bug?

**Comment by odlevakp** [comment] 2017-06-07 13:44
Sure, when I close all panels it's till there 2x. Once I start opening files, new panels are added only under the first one, second one remains empty. 

It might be just my atom installation, can try later on another computer, since even going `File/New File` throws an exception (unrelated to this issue)
```Uncaught TypeError: Cannot read property 'nextSibling' of undefined```


Here are details:

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Version**: [open-files](https://github.com/oriolmirosa/open-files) package 0.6.1


### Non-Core Packages

```
atom-beautify undefined 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.7 
git-log 0.4.1 
git-tab-status 1.9.2 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.2 
language-chef 0.9.0 
language-docker 1.1.8 
language-generic-config 1.3.0 
language-nginx 0.8.0 
linter 2.1.4 
linter-shellcheck 1.4.4 
linter-ui-default 1.6.0 
minimap 4.28.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
open-files 0.6.1 
project-manager 3.3.5 
remote-atom 1.3.10 
tab-smart-sort 0.3.0 
```

**Comment by oriolmirosa** [comment] 2017-06-07 18:47
If, when you have several files open and the 2x 'open files' panels are visible, you press Control + Option + Command + L and Atom reloads, do the problems persist? At this point I can't reproduce this, but I will probably have to rewrite much of the package to make it work with the upcoming Atom 1.18 (it is totally broken with the beta), and so it might make sense to leave this bug open until the new version comes out and we can see if this still happens. Sorry for the troubles!

**Comment by oriolmirosa** [comment] 2017-06-08 02:52
Hi, @odlevakp. You were right about the problems with the `Uncaught TypeError: Cannot read property 'nextSibling' of undefined` error. I think I fixed that in 0.6.2. Can you please take a look and let me know if the problem persists? Also, if the problem is fixed, could you tell me if the issue with 2x 'open files' is still there? I have not been able to reproduce that one. Thanks!

**Comment by vvs** [comment] 2017-06-08 07:32
> to rewrite much of the package to make it work with the upcoming Atom 1.18 (it is totally broken with the beta)

This is news for me, open-files 0.6.1, as well as 0.6.2 works great on 1.18 :)

**Comment by odlevakp** [comment] 2017-06-08 08:35
@oriolmirosa Thanks for that exception fix!

As for the 2x Open Files issue, I wasn't able to replicate on my Ubuntu box, then found out what caused it - basically my atom editor had 2 split panes opened, where one was dragged to the edge and invisible. I don't know why atom didn't close that empty pane (when trying to replicate, it always did), but that's why I saw the second Open Files entry as empty.

**Comment by oriolmirosa** [comment] 2017-06-08 13:46
Alright, I'm closing this bug then. Thanks for the help, @odlevakp. @vvs funny that 0.6.1 worked for you. It was a mess for me. Hopefully 0.6.2 works for everybody.

**Closed as completed by oriolmirosa** 2017-06-08 13:46 UTC
