### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by gtozzi** [oriolmirosa/open-files#15] opened 2017-06-01 13:45 UTC
This is a very useful package, thank you!!!

Would it be possible to also have files icons? (the same icons that are displayed on tree view)

**Comment by oriolmirosa** [comment] 2017-06-01 13:59
The package already shows the same icons as in the tree view. The problem is that they don't appear when you first create a file. But if you reload Atom after the file has been created (command + J + K + L in a Mac), or if you close the file and then open it again, the icon should be there. Is that not the case for you?

In any case, I'll leave the bug open so that I can work on making sure that the icon is loaded on file creation. Thanks for the feedback!

**Comment by gtozzi** [comment] 2017-06-01 14:24
Nope, this is what i see even after restarting atom:

![Screen](http://picpaste.com/pics/screen4-9HT26Di7.1496326975.jpg)

Thank you for your reply!

**Comment by oriolmirosa** [comment] 2017-06-01 14:31
Hmm... then I need more info so that I can reproduce the problem and see what the issue is, because it works in my machine. Can you tell me what your system is and what packages you have loaded (particularly any packages that affect the icons)? Thanks!

**Comment by gtozzi** [comment] 2017-06-01 14:41
Atom 1.17.2 x64 on Linux

Packages:
- atom-typescript
- busy-signal
- **file-icons**
- github-atom-light-syntax
- intentions
- linter
- linter-ui-default
- minimap
- open-files
- pigments
- project-plus
- symbols-tree-view
- tab-control
- todo-show

Following your hint, i tried disabling the _file-icons_ package and then restarting atom, nothing changed.

**Comment by oriolmirosa** [comment] 2017-06-01 14:46
Thanks for the quick response. I see what the problem is. I use the seti-icons package, not file-icons. When I switch to file-icons I have the same problem as you. I'll have to investigate what the issue is with the package and look for a solution. I'm pretty busy at the moment since I just moved to a new state and I'm looking for a job, but I'll try to get to this as soon as I can.

**Comment by gtozzi** [comment] 2017-06-01 14:51
Thank you, good luck for you job!

**Comment by vvs** [comment] 2017-06-05 20:12
I can confirm that file-icons are not shown for me as well. All i see is the generic file icon for every file (no matter the extension).

Oh, and btw, I also found that in some fork of this project, there is the file-icons support implemented:
https://github.com/davidashman/working-files/commit/68fd7a9452a64e9b54e2d00589e0b8abec55aaba

**Comment by oriolmirosa** [comment] 2017-06-06 14:01
Thanks for your feedback and comments. 0.6.1 should have this fixed, so now the icons both from the file-icons and the seti-icons packages should appear properly in the 'open files' panel. I'm closing the bug, but please let me know if there are any problems and we can re-open it. Thanks again!

**Closed as completed by oriolmirosa** 2017-06-06 14:01 UTC

**Comment by gtozzi** [comment] 2017-06-06 14:06
I confirm it works for me. Thank you.

**Comment by vvs** [comment] 2017-06-06 16:33
Excellent, it works for me as well! Many thanks!
